name: portfolio_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^15.1.2
  flutter_svg: ^2.1.0
  url_launcher: ^6.3.1
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/dizzycat/
    - assets/images/studymate/
    - assets/images/mysnowyfriend/
    - assets/svgs/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
